name: Bug report
description: 'Create a new bug report.'
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: >-
        # 💎 Bounty program (with
        [algora.io](https://console.algora.io/org/coollabsio/bounties/new))


        If you would like to prioritize the issue resolution, you can add bounty
        to this issue.


        Click [here](https://console.algora.io/org/coollabsio/bounties/new) to
        get started.
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem
  - type: textarea
    attributes:
      label: Minimal Reproduction (if possible, example repository)
      description: Please provide a step by step guide to reproduce the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Exception or Error
      description: Please provide error logs if possible.
  - type: input
    attributes:
      label: Version
      description: Coolify's version (see top of your screen).
    validations:
      required: true
